// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const topBar: string;
export const search: string;
export const searchContainer: string;
export const inputContainer: string;
